### ISSUE TITLE
Unable to find Ruby

### ISSUE THREAD

**Issue by asbjornu** [claui/homebrew-whence#1]
Thanks for making this great command! I've installed the `ruby` formula and `whence` is unable to find it:

```sh
$ brew whence ruby
Error: ruby: no such file in any of /usr/local/bin, /usr/local/sbin
```

`which ruby` reveals that the `ruby` binary is installed in `/usr/local/opt/ruby/bin/ruby`, which is a symlink to `/usr/local/Cellar/ruby/3.2.2_1/bin/ruby`.

**Comment by claui** [comment]
Hi @asbjornu, thanks for the kind words. Sorry but I can’t help with that issue as I no longer use Homebrew.
